baseURL = "https://andreabredice.dev/"
languageCode = "en-us"
title = "Andrea Bredice - Be Dev"
theme                    = "sam"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]

    author = "Andrea Bredice"
    title                = "Andrea Bredice - Be Dev"
    sitename = "Andrea Bredice - Be Dev"
    description          = "Hello World, I am Andrea Bredice! Motto: the achievement of the objectives is just as important as the path followed to get them."               # Max 160 characters show in search results
    images               = ["preview.png"]
    homepage = "home"
    og_image = "/images/preview.png"
    favicon              = "ab.ico"
    footerText           = "Hosted on Netlify thanks to GitHub, Sam and Hugo - we're all best friends."

    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"

    github = "https://github.com/dasher7"
    facebook = "https://www.facebook.com/andrebredi"
    twitter = "@andreabredi"
    instagram = "@andrea_bredice"

[[params.mainMenu]]
    link = "/projects"
    text = "Projects"

[[params.mainMenu]]
    link = "/skill"
    text = "Skill"

[[params.mainMenu]]
    link = "/contact"
    text = "Contact me"

[[params.mainMenu]]
    link = "/about"
    text = "About Andrea"
